apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-app-5
spec:
  selector:
    matchLabels:
      app: php-app-5
  template:
    metadata:
      labels:
        app: php-app-5
    spec:
      containers:
        - name: php-app-5
          image: thiagost32/php-app-5:1.0
          replicas: 3
          imagePullPolicy: always
          ports:
           - containerPort: 80


---

apiVersion: v1
kind: Service
metadata:
  app: php-service
spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30010
  selector:
    app: php-app-5